name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY_NAME: dsmsacr
  CLUSTER_NAME: ds-ms
  CLUSTER_RESOURCE_GROUP: ds-ms
  NAMESPACE: demo-e2e

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Check resource policy compliance post deployment
      uses: ajinkya599/AzPac@azpac-initial
      with:
        scopes: |
          /subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourcegroups/az-pac-demo/providers/Microsoft.Web/sites/e2edemoapp


          